# Generated by Django 3.1.1 on 2021-02-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='zip',
            field=models.CharField(max_length=50),
        ),
    ]
